### ISSUE TITLE
Deploy Cognito

### ISSUE THREAD

**Issue by hindeb** [bahrain-bp/mun-aquacrop#42]
define identity pool and attributes for user

**Comment by izZERO** [comment]
**Updates:**

 * - Implemented a custom authentication system using AWS Cognito with custom challenge Lambdas.
 * - Created Lambda functions for defining, creating, and verifying custom authentication challenges.
 * - Integrated AWS SNS for sending SMS-based OTP (One-Time Password) as part of the custom challenge flow.
 * - Successfully tested the authentication flow using AWS CLI and confirmed successful generation and verification of tokens.


 **Next steps:**

 *   - Replace the current SMS OTP implementation with Amazon Pinpoint to eliminate the need for verified users before sending SMS messages(Solves Account SandBox Issue).
 *   - Implement the solution to the frontend after the frontend is completed by other team members.

**Comment by izZERO** [comment]
Updates:
- tried implementing Amazon pinpoint but appearently amazon are in the process of rebranding the service and changing it into other service callled End User Messaging which also requires the verified user before an sms is sent and is way more complicated than the current simple setup, i tried implementing it but failed due to it requiring an actual number to send messages from which is requested from amazon. 
- updated the code to have more security features like an expiration time for otp and a retry limit for improved security.
- currently working on the integration with the frontend as its not fully completed

**Comment by izZERO** [comment]
- [ ] Implement & Integrate Apis with Auth
- [ ] Create Auth Screen as a frontend
- [ ] Add Fullname into the Auth System as requested by customer and adjust apis
- [ ] Update Navigation to Dashboard
- [ ] Export User data to database
- [ ] Make Sure Auth fully Works
